Program(FunDecl(INT,main,
	Block(If(IntLiteral(1),
			Block(If(IntLiteral(2),
					Block(Return(IntLiteral(1))
					),
						Block(Return(IntLiteral(2))
						)),
				Return(IntLiteral(2))
					)),
		Return()
				)))